# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

stages:
  - stage: Run_Tests
    displayName: 'Run Tests'
    jobs:
      - job: test_job
        displayName: 'Run WDIO Tests'
        pool:
          vmImage: ubuntu-latest
        steps:
          - task: BrowserStackConfig@0
            inputs:
              BrowserStackServiceEndPoint: 'BrowserstackCI'

          - script: |
              set -x
              npm install
            displayName: 'npm install'

          - script: |
              set -x
              npm run sample-test
            displayName: 'Run Tests'

  - stage: BrowserStack_Report
    displayName: 'BrowserStack Reporting'
    dependsOn: Run_Tests
    condition: always()  # ✅ ensures this stage runs even if tests failed
    jobs:
      - job: report_job
        displayName: 'Generate BStack Report'
        pool:
          vmImage: ubuntu-latest
        steps:
          - task: BrowserStackConfig@0
            inputs:
              BrowserStackServiceEndPoint: 'BrowserstackCI'
              
          - task: BrowserStackResults@1
            inputs:
              reportTimeout: '130'
